# Generated by Django 2.2 on 2019-10-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypePolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new', 'New'), ('end', 'End')], max_length=40)),
                ('date', models.DateTimeField()),
                ('username', models.CharField(max_length=200)),
                ('client_ip', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new', 'New'), ('end', 'End')], max_length=40)),
                ('date', models.DateTimeField()),
                ('username', models.CharField(max_length=200)),
                ('client_ip', models.CharField(max_length=200)),
                ('simulation_type', models.CharField(max_length=200)),
                ('exercise_id', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=200)),
                ('container_id', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
    ]
