# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, b'New'), (2, b'End')])),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=200)),
                ('client_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(3, b'New'), (4, b'End')])),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=200)),
                ('client_ip', models.GenericIPAddressField()),
                ('simulation_type', models.CharField(max_length=200)),
                ('exercise_id', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=200)),
                ('container_id', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
            ],
        ),
    ]
